title: "What To Do?"
theme: minima

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

markdown: kramdown

repository: "amylzting/whattodo/"
github_icon: "images/github-icon.png"

plugins:
  - jemoji
